// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import { useState } from 'react';

export const useForgotPassword = () => {
  const API_URL = import.meta.env.VITE_API_URL;
  const [email, setEmail] = useState('');
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');
  const [warning, setWarning] = useState('');
  const [info, setInfo] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setWarning('');
    setInfo('');
    setLoading(true);

    try {
      const response = await fetch(`${API_URL}/api/auth/password-reset/request`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email }),
      });

      if (!response.ok) {
        setError('Something went wrong. Please try again.');
        return;
      }

      const data = await response.json();
      setSuccess(data.message ?? 'If the account exists, a password reset email has been sent');
    } catch {
      setError('Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return { email, setEmail, success, error, warning, info, loading, handleSubmit };
};
