// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

// @ts-nocheck
import { useEffect, useState } from 'react';
import { applyPasswordEyeIcon } from './passwordToggleIcons';

/**
 * useLogin
 * Handles authentication against the Cloudey API.
 * Edit this file to customize login behaviour.
 *
 * Password eye: same contract as bss-export/assets/js/cloudey.js (#pwToggle, #password,
 * #eyeIcon). Input type is driven by React state (controlled field); icon uses innerHTML
 * swap like cloudey.js.
 */
export const useLogin = () => {
  const API_URL = import.meta.env.VITE_API_URL;
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  useEffect(() => {
    const pwToggle = document.getElementById('pwToggle');
    const handler = () => setShowPassword((v) => !v);
    pwToggle?.addEventListener('click', handler);
    return () => pwToggle?.removeEventListener('click', handler);
  }, []);

  useEffect(() => {
    applyPasswordEyeIcon(showPassword);
  }, [showPassword]);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [warning, setWarning] = useState('');
  const [info, setInfo] = useState('');
  const [loading, setLoading] = useState(false);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setWarning('');
    setInfo('');
    setLoading(true);

    try {
      const formData = new FormData();
      formData.append('username', email);
      formData.append('password', password);

      const response = await fetch(`${import.meta.env.VITE_API_URL}/api/auth/login/token`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        setError('Invalid email or password. Please try again.');
        return;
      }

      const data = await response.json();
      localStorage.setItem('cloudey_access_token', data.access_token);

      setSuccess('You have been successfully logged in.');

      const redirect = async () => {
        try {
          const meRes = await fetch(`${API_URL}/api/identity/users/me`, {
            headers: { Authorization: `Bearer ${data.access_token}` },
          });
          if (meRes.ok) {
            const me = await meRes.json();
            window.location.href = me?.user_type === 'staff' ? '/admin/overview' : '/';
          } else {
            window.location.href = '/';
          }
        } catch {
          window.location.href = '/';
        }
      };

      window.setTimeout(() => {
        void redirect();
      }, 800);
    } catch {
      setError('Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return {
    email,
    setEmail,
    password,
    setPassword,
    showPassword,
    error,
    success,
    warning,
    info,
    loading,
    handleLogin,
  };
};
