// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import { useEffect } from 'react';
import { applyPasswordEyeIcon } from './passwordToggleIcons';

/**
 * Password show/hide — port of cloudey.js (#pwToggle, #password, #eyeIcon).
 * Used on shell pages via useCloudey (login uses useLogin + React state for input.type).
 */
export function usePasswordToggle() {
  useEffect(() => {
    const pwToggle = document.getElementById('pwToggle');
    if (!pwToggle) return;

    const handler = () => {
      const input = document.getElementById('password') as HTMLInputElement | null;
      if (!input) return;
      const showing = input.type === 'text';
      input.type = showing ? 'password' : 'text';
      applyPasswordEyeIcon(!showing);
    };

    pwToggle.addEventListener('click', handler);
    return () => pwToggle.removeEventListener('click', handler);
  }, []);
}
