// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import { useEffect, useState } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { applyPasswordEyeIcon, EYE_OPEN, EYE_SLASH } from './passwordToggleIcons';

const API_URL = import.meta.env.VITE_API_URL ?? '';

export const useResetPassword = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const token = searchParams.get('token') ?? '';

  const [password, setPassword] = useState('');
  const [passwordConfirm, setPasswordConfirm] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showPasswordConfirm, setShowPasswordConfirm] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [warning, setWarning] = useState('');
  const [info, setInfo] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!token) {
      setError('Invalid or expired reset link. Request a new one.');
    }
  }, [token]);

  useEffect(() => {
    const pwToggle = document.getElementById('pwToggle');
    const handler = () => setShowPassword((v) => !v);
    pwToggle?.addEventListener('click', handler);
    return () => pwToggle?.removeEventListener('click', handler);
  }, []);

  useEffect(() => {
    applyPasswordEyeIcon(showPassword);
  }, [showPassword]);

  useEffect(() => {
    const pwToggle = document.getElementById('pwToggleConfirm');
    const handler = () => setShowPasswordConfirm((v) => !v);
    pwToggle?.addEventListener('click', handler);
    return () => pwToggle?.removeEventListener('click', handler);
  }, []);

  useEffect(() => {
    const icon = document.getElementById('eyeIconConfirm');
    if (icon) icon.innerHTML = showPasswordConfirm ? EYE_SLASH : EYE_OPEN;
  }, [showPasswordConfirm]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setWarning('');
    setInfo('');

    if (!token) {
      setError('Invalid or expired reset link. Request a new one.');
      return;
    }
    if (password !== passwordConfirm) {
      setError("Passwords don't match.");
      return;
    }
    if (password.length < 8) {
      setWarning('Use at least 8 characters with a mix of letters and numbers.');
      return;
    }

    setLoading(true);
    try {
      const res = await fetch(`${API_URL}/api/auth/password-reset/confirm`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, new_password: password }),
      });
      if (!res.ok) {
        setError('Invalid or expired reset link. Request a new one.');
        return;
      }
      const data = await res.json();
      setSuccess(data.message ?? 'Your password has been updated. You can sign in now.');
      window.setTimeout(() => navigate('/login'), 1500);
    } catch {
      setError('Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return {
    password,
    setPassword,
    passwordConfirm,
    setPasswordConfirm,
    showPassword,
    showPasswordConfirm,
    error,
    success,
    warning,
    info,
    loading,
    handleSubmit,
  };
};
