// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import React from 'react';
import CustomerShell from '../../layout/CustomerShell';

const ResourcesPage: React.FC = () => {
  return (
    <CustomerShell>
      <div className="container-fluid" style={{maxWidth: '1200px', padding: '32px 32px 80px'}}>
                  <div className="mb-4">
                      <h1 className="fw-bold text-body mb-1 h4">Resource Inventory</h1><small className="text-muted">All OCI resources across regions · sorted by monthly cost</small>
                  </div>
                  <div className="row mb-4 g-3">
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body"><small className="fw-medium text-muted d-block mb-3">Total Resources</small>
                                  <div className="text-body stat-value"><span>17</span></div><small className="text-muted">Across OCI</small>
                              </div>
                          </div>
                      </div>
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body"><small className="fw-medium text-muted d-block mb-3">Running</small>
                                  <div className="text-success stat-value"><span>10</span></div><small className="text-muted">Active and billing</small>
                              </div>
                          </div>
                      </div>
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body"><small className="fw-medium text-muted d-block mb-3">Idle</small>
                                  <div className="text-warning stat-value"><span>4</span></div><small className="text-muted">Low utilization</small>
                              </div>
                          </div>
                      </div>
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body"><small className="fw-medium text-muted d-block mb-3">Unattached</small>
                                  <div className="text-danger stat-value"><span>3</span></div><small className="text-muted">Pure waste</small>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="card border shadow-sm">
                      <div className="card-body p-4">
                          <div className="d-flex align-items-center flex-wrap gap-3 mb-4">
                              <div className="input-group" style={{maxWidth: '320px'}}><span className="text-muted bg-body-secondary input-group-text border-end-0"><svg className="bi bi-search" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '12px'}}>
                                          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"></path>
                                      </svg></span><input className="bg-body-secondary form-control border-start-0" type="text" placeholder="Search by name, type, region…" style={{fontSize: '13px'}} /></div>
                              <ul className="nav nav-pills gap-1 mb-0" role="tablist">
                                  <li className="nav-item"><button className="active nav-link btn-sm" data-bs-toggle="pill" data-bs-target="#rAll">All</button></li>
                                  <li className="nav-item"><button className="nav-link btn-sm" data-bs-toggle="pill" data-bs-target="#rRunning">Running</button></li>
                                  <li className="nav-item"><button className="nav-link btn-sm" data-bs-toggle="pill" data-bs-target="#rIdle">Idle</button></li>
                                  <li className="nav-item"><button className="nav-link btn-sm" data-bs-toggle="pill" data-bs-target="#rUnattached">Unattached</button></li>
                              </ul>
                          </div>
                          <div className="tab-content">
                              <div className="tab-pane fade show active" role="tabpanel" id="rAll">
                                  <div>
                                      <table className="table table-hover align-middle">
                                          <thead>
                                              <tr>
                                                  <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Resource</th>
                                                  <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Type</th>
                                                  <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Region</th>
                                                  <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Status</th>
                                                  <th className="text-uppercase fw-semibold text-end text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Cost/mo</th>
                                              </tr>
                                          </thead>
                                          <tbody>
                                              <tr>
                                                  <td><span className="bg-danger rounded-circle d-inline-block me-1" style={{width: '6px', height: '6px', verticalAlign: 'middle'}}></span><span className="fw-medium text-body" style={{fontSize: '13px'}}>data-pipeline-prod</span></td>
                                                  <td><small className="text-muted">VM.Standard3.Flex</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-success-emphasis bg-success-subtle rounded-pill" style={{fontSize: '11px'}}>running</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$1,820</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="fw-medium text-body" style={{fontSize: '13px'}}>analytics-cluster-01</span></td>
                                                  <td><small className="text-muted">VM.Standard2.24</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-success-emphasis bg-success-subtle rounded-pill" style={{fontSize: '11px'}}>running</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$1,200</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="fw-medium text-body" style={{fontSize: '13px'}}>mysql-prod</span></td>
                                                  <td><small className="text-muted">MySQL HeatWave</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-success-emphasis bg-success-subtle rounded-pill" style={{fontSize: '11px'}}>running</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$1,200</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="fw-medium text-body" style={{fontSize: '13px'}}>app-server-01</span></td>
                                                  <td><small className="text-muted">VM.Standard2.4</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-success-emphasis bg-success-subtle rounded-pill" style={{fontSize: '11px'}}>running</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$640</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="fw-medium text-body" style={{fontSize: '13px'}}>lb-production</span></td>
                                                  <td><small className="text-muted">Load Balancer 100Mbps</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-success-emphasis bg-success-subtle rounded-pill" style={{fontSize: '11px'}}>running</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$560</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="bg-danger rounded-circle d-inline-block me-1" style={{width: '6px', height: '6px', verticalAlign: 'middle'}}></span><span className="fw-medium text-body" style={{fontSize: '13px'}}>analytics-dev</span></td>
                                                  <td><small className="text-muted">VM.Standard2.8</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-warning-emphasis bg-warning-subtle rounded-pill" style={{fontSize: '11px'}}>idle</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$480</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="fw-medium text-body" style={{fontSize: '13px'}}>object-storage-backup</span></td>
                                                  <td><small className="text-muted">Object Storage</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-success-emphasis bg-success-subtle rounded-pill" style={{fontSize: '11px'}}>running</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$480</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="bg-danger rounded-circle d-inline-block me-1" style={{width: '6px', height: '6px', verticalAlign: 'middle'}}></span><span className="fw-medium text-body" style={{fontSize: '13px'}}>mysql-staging</span></td>
                                                  <td><small className="text-muted">MySQL VM.Standard.E3.1.8</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-warning-emphasis bg-warning-subtle rounded-pill" style={{fontSize: '11px'}}>idle</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$240</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="bg-danger rounded-circle d-inline-block me-1" style={{width: '6px', height: '6px', verticalAlign: 'middle'}}></span><span className="fw-medium text-body" style={{fontSize: '13px'}}>storage-backup-01</span></td>
                                                  <td><small className="text-muted">Block Volume 2TB</small></td>
                                                  <td><small className="text-muted">ap-sydney-1</small></td>
                                                  <td><span className="badge fw-semibold text-danger-emphasis bg-danger-subtle rounded-pill" style={{fontSize: '11px'}}>unattached</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$200</td>
                                              </tr>
                                              <tr>
                                                  <td><span className="fw-medium text-body" style={{fontSize: '13px'}}>singapore-db</span></td>
                                                  <td><small className="text-muted">MySQL VM.Standard.E3</small></td>
                                                  <td><small className="text-muted">ap-singapore-1</small></td>
                                                  <td><span className="badge fw-semibold text-success-emphasis bg-success-subtle rounded-pill" style={{fontSize: '11px'}}>running</span></td>
                                                  <td className="fw-semibold text-end text-body" style={{fontSize: '13px'}}>$320</td>
                                              </tr>
                                          </tbody>
                                      </table>
                                  </div>
                                  <div className="d-flex justify-content-between align-items-center pt-3 border-top"><small className="text-muted">Showing 1–10 of 17</small>
                                      <div className="d-flex gap-2"><button className="btn btn-outline-secondary btn-sm disabled" disabled>Prev</button><button className="btn btn-outline-secondary btn-sm">Next</button></div>
                                  </div>
                              </div>
                              <div className="tab-pane fade" role="tabpanel" id="rRunning">
                                  <p className="text-muted mt-3" style={{fontSize: '13px'}}>Showing running resources.</p>
                              </div>
                              <div className="tab-pane fade" role="tabpanel" id="rIdle">
                                  <p className="text-muted mt-3" style={{fontSize: '13px'}}>Showing idle resources.</p>
                              </div>
                              <div className="tab-pane fade" role="tabpanel" id="rUnattached">
                                  <p className="text-muted mt-3" style={{fontSize: '13px'}}>Showing unattached resources.</p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
    </CustomerShell>
  );
};

export default ResourcesPage;
