// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import React from 'react';
import { useForgotPassword } from '../hooks/useForgotPassword';

const ForgotPasswordPage: React.FC = () => {
  const { email, setEmail, success, error, handleSubmit } = useForgotPassword();
  return (
    <>
      <div id="forgotPassword">
      <div id="glow1"></div>
          <div id="glow2"></div>
          <div id="glow3"></div>
          <div className="card border rounded-4 shadow p-4 p-sm-5 mx-3" id="loginCard">
              <div className="text-center mb-4"><img src="/logo-cloudey.png" alt="Cloudey" style={{height: '52px', width: 'auto'}} /></div>
              <h1 className="fw-bold text-center text-body mb-1 h5" style={{letterSpacing: '-.5px'}}><strong>Reset your password</strong></h1>
              <p className="text-center text-muted mb-4" style={{fontSize: '14px'}}>Enter your email and we'll send reset instructions if an account exists.</p>
              {error && (
            <div className="alert alert-danger d-flex align-items-center gap-2 mb-3 py-2" role="alert" style={{fontSize: '13px'}}>
              <span>{error}</span>
            </div>
          )}
              {success && (
            <div className="alert alert-success align-items-center gap-2 mb-3 py-2" role="alert" style={{fontSize: '13px'}}>
              <span>{success}</span>
            </div>
          )}
              <form id="loginForm" noValidate data-cloudey="forgot_password.form" onSubmit={handleSubmit}>
                  <div className="mb-3"><label className="form-label fw-semibold" htmlFor="email" style={{fontSize: '13px'}}>Email</label>
                      <div className="input-group"><span className="text-muted bg-body-secondary input-group-text border-end-0"><svg className="bi bi-envelope" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1zm13 2.383-4.708 2.825L15 11.105zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741M1 11.105l4.708-2.897L1 5.383z"></path>
                              </svg></span><input className="bg-body-secondary form-control border-start-0" type="email" id="email" autoComplete="email" name="email" placeholder="alex@company.com" required style={{fontSize: '14px'}} data-cloudey="forgot_password.email" value={email} onChange={e => setEmail(e.target.value)} /></div>
                  </div><button className="btn btn-primary fw-semibold w-100 mb-4" type="submit" id="loginBtn" style={{fontSize: '15px', padding: '12px'}}> Send reset link</button>
              </form>
              <div className="small text-center gap-3"><a className="text-decoration-none" href="/login">Back to sign in</a></div>
          </div>
    
    
      </div>
    </>
  );
};

export default ForgotPasswordPage;
