// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import React from 'react';
import { useResetPassword } from '../hooks/useResetPassword';

const ResetPasswordPage: React.FC = () => {
  const { password, setPassword, passwordConfirm, setPasswordConfirm, showPassword, showPasswordConfirm, error, success, warning, handleSubmit } = useResetPassword();
  return (
    <>
      <div id="resetPassword">
      <div id="glow1"></div>
          <div id="glow2"></div>
          <div id="glow3"></div>
          <div className="card border rounded-4 shadow p-4 p-sm-5 mx-3" id="loginCard">
              <div className="text-center mb-4"><img src="/logo-cloudey.png" alt="Cloudey" style={{height: '52px', width: 'auto'}} /></div>
              <h1 className="fw-bold text-center text-body mb-1 h5" style={{letterSpacing: '-.5px'}}><strong>Choose a new password</strong></h1>
              <p className="text-center text-muted mb-4" style={{fontSize: '14px'}}>Enter a strong password for your account. You'll use it the next time you sign in.</p>
              {error && (
            <div className="alert alert-danger d-flex align-items-center gap-2 mb-3 py-2" role="alert" style={{fontSize: '13px'}}>
              <span>{error}</span>
            </div>
          )}
              {warning && (
            <div className="alert alert-warning align-items-center gap-2 mb-3 py-2" role="alert" style={{fontSize: '13px'}}>
              <span>{warning}</span>
            </div>
          )}
              {success && (
            <div className="alert alert-success align-items-center gap-2 mb-3 py-2" role="alert" style={{fontSize: '13px'}}>
              <span>{success}</span>
            </div>
          )}
              <form id="resetPasswordForm" noValidate data-cloudey="reset_password.form" onSubmit={handleSubmit}>
                  <div className="mb-3"><label className="form-label fw-semibold" htmlFor="password" style={{fontSize: '13px'}}>New Password</label>
                      <div className="input-group position-relative"><span className="text-muted bg-body-secondary input-group-text border-end-0"><svg className="bi bi-lock" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                  <path fillRule="evenodd" d="M8 0a4 4 0 0 1 4 4v2.05a2.5 2.5 0 0 1 2 2.45v5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 13.5v-5a2.5 2.5 0 0 1 2-2.45V4a4 4 0 0 1 4-4M4.5 7A1.5 1.5 0 0 0 3 8.5v5A1.5 1.5 0 0 0 4.5 15h7a1.5 1.5 0 0 0 1.5-1.5v-5A1.5 1.5 0 0 0 11.5 7zM8 1a3 3 0 0 0-3 3v2h6V4a3 3 0 0 0-3-3"></path>
                              </svg></span><input className="bg-body-secondary form-control pe-5 border-start-0 border-end-0" type="password" id="password" autoComplete="new-password" name="password" placeholder="••••••••" required style={{fontSize: '14px'}} data-cloudey="reset_password.password" value={password} onChange={e => setPassword(e.target.value)} type={showPassword ? 'text' : 'password'} /><button aria-label="Show password" id="pwToggle" type="button"><svg className="bi bi-eye" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" id="eyeIcon" style={{fontSize: '14px'}}>
                                  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                              </svg></button></div>
                  </div>
                  <div className="mb-3"><label className="form-label fw-semibold" htmlFor="passwordConfirm" style={{fontSize: '13px'}}>Confirm Password</label>
                      <div className="input-group position-relative"><span className="text-muted bg-body-secondary input-group-text border-end-0"><svg className="bi bi-lock" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                  <path fillRule="evenodd" d="M8 0a4 4 0 0 1 4 4v2.05a2.5 2.5 0 0 1 2 2.45v5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 13.5v-5a2.5 2.5 0 0 1 2-2.45V4a4 4 0 0 1 4-4M4.5 7A1.5 1.5 0 0 0 3 8.5v5A1.5 1.5 0 0 0 4.5 15h7a1.5 1.5 0 0 0 1.5-1.5v-5A1.5 1.5 0 0 0 11.5 7zM8 1a3 3 0 0 0-3 3v2h6V4a3 3 0 0 0-3-3"></path>
                              </svg></span><input className="bg-body-secondary form-control pe-5 border-start-0 border-end-0" type="password" id="passwordConfirm" autoComplete="new-password" name="password_confirm" placeholder="••••••••" required style={{fontSize: '14px'}} data-cloudey="reset_password.password_confirm" value={passwordConfirm} onChange={e => setPasswordConfirm(e.target.value)} type={showPasswordConfirm ? 'text' : 'password'} /><button id="pwToggleConfirm" aria-label="Show password" type="button"><svg className="bi bi-eye" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" id="eyeIconConfirm" style={{fontSize: '14px'}}>
                                  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                              </svg></button></div>
                  </div>
                  <div className="mb-3">
                      <p className="small text-start text-muted">At least 8 characters<br />Mix of letters and numbers<br />Avoid common words</p>
                  </div><button className="btn btn-primary fw-semibold w-100 mb-4" id="UpdatePasswordBtn" type="submit" style={{fontSize: '15px', padding: '12px'}}> Update password</button>
              </form>
              <div className="small text-center gap-3"><a className="text-decoration-none" href="/login">Back to sign in</a><span className="text-muted mx-2">·</span><a className="text-decoration-none" href="/forgot-password">Request a new link</a></div>
          </div>
    
    
      </div>
    </>
  );
};

export default ResetPasswordPage;
