// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

// @ts-nocheck
import React from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

/**
 * ProtectedRoute
 * Redirects to /login if no token is found in localStorage.
 * Auto-generated by bss_to_react.py — do not edit manually.
 */
const ProtectedRoute = ({ children }: { children: React.ReactNode }) => {
  const location = useLocation();
  const { user, isLoading } = useAuth();
  const token = localStorage.getItem('cloudey_access_token');

  if (!token) {
    return <Navigate to="/login" replace />;
  }

  if (isLoading) {
    return null;
  }

  if (!user) {
    return <Navigate to="/login" replace />;
  }

  const isAdminPath = location.pathname.startsWith('/admin');
  const isStaff = user.user_type === 'staff';

  // Customers can never access admin pages.
  if (isAdminPath && !isStaff) {
    return <Navigate to="/" replace />;
  }


  return <>{children}</>;
};

export default ProtectedRoute;
