// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import { Modal } from 'bootstrap';

/**
 * Bootstrap is loaded twice in the Vite app:
 * - `bootstrap.bundle.min.js` in main.tsx (handles data-bs-toggle / data-bs-dismiss)
 * - ESM `Modal` import here
 *
 * Modals opened via data-bs-toggle use the bundle instance. Closing with only the ESM
 * `Modal.hide()` can leave `.modal-backdrop` on the page. Prefer dismiss clicks + cleanup.
 */

function getModalConstructor(): typeof Modal {
  return (window as Window & { bootstrap?: { Modal: typeof Modal } }).bootstrap?.Modal ?? Modal;
}

/** Remove stuck backdrop / body lock when no modal is visible. */
export function removeOrphanModalChrome() {
  if (document.querySelector('.modal.show')) return;
  document.querySelectorAll('.modal-backdrop').forEach((el) => el.remove());
  document.body.classList.remove('modal-open');
  document.body.style.removeProperty('overflow');
  document.body.style.removeProperty('padding-right');
}

function scheduleModalChromeCleanup(modalEl: HTMLElement) {
  modalEl.addEventListener('hidden.bs.modal', () => removeOrphanModalChrome(), { once: true });
  window.setTimeout(removeOrphanModalChrome, 400);
}

/**
 * Close the Bootstrap 5 modal that wraps this form.
 */
export function closeModalFromForm(form: HTMLFormElement | null) {
  const modalEl = form?.closest('.modal') as HTMLElement | null;
  if (!modalEl) return;

  const dismiss = modalEl.querySelector<HTMLElement>('[data-bs-dismiss="modal"]');
  if (dismiss) {
    dismiss.click();
  } else {
    const ModalCtor = getModalConstructor();
    const inst = ModalCtor.getInstance(modalEl) ?? ModalCtor.getOrCreateInstance(modalEl);
    inst.hide();
  }

  scheduleModalChromeCleanup(modalEl);
}

/** Close a modal by its root element id (e.g. `createNewOCIConnection`). */
export function hideModalByElementId(elementId: string) {
  const el = document.getElementById(elementId);
  if (!el) return;

  const dismiss = el.querySelector<HTMLElement>('[data-bs-dismiss="modal"]');
  if (dismiss) {
    dismiss.click();
  } else {
    const ModalCtor = getModalConstructor();
    const inst = ModalCtor.getInstance(el) ?? ModalCtor.getOrCreateInstance(el);
    inst.hide();
  }

  scheduleModalChromeCleanup(el);
}
