import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { AuthProvider } from './context/AuthContext';
import AppLayout from './layout/AppLayout';
import ProtectedRoute from './components/ProtectedRoute';
import CompaniesPage from './pages/admin/CompaniesPage';
import MembershipsPage from './pages/admin/MembershipsPage';
import OverviewPage from './pages/admin/OverviewPage';
import UsersPage from './pages/admin/UsersPage';
import AnomaliesPage from './pages/customer/AnomaliesPage';
import CostExplorerPage from './pages/customer/CostExplorerPage';
import IndexPage from './pages/customer/IndexPage';
import ProfilePage from './pages/ProfilePage';
import ReportsPage from './pages/customer/ReportsPage';
import ResourcesPage from './pages/customer/ResourcesPage';
import SavingsPage from './pages/customer/SavingsPage';
import SettingsPage from './pages/customer/SettingsPage';
import ForgotPasswordPage from './pages/ForgotPasswordPage';
import LayoutPage from './pages/LayoutPage';
import LoginPage from './pages/LoginPage';
import ResetPasswordPage from './pages/ResetPasswordPage';

/**
 * App — auto-generated by bss_to_react.py. Do not edit manually.
 */
function App() {
  return (
    <AuthProvider>
      <BrowserRouter>
        <Routes>
          {/* Auth pages — no layout, no protection */}
        <Route path="/forgot-password" element={<ForgotPasswordPage />} />
        <Route path="/login" element={<LoginPage />} />
        <Route path="/reset-password" element={<ResetPasswordPage />} />
          {/* Authenticated pages — protected + AppLayout */}
          <Route element={<ProtectedRoute><AppLayout /></ProtectedRoute>}>
          <Route path="/admin/companies" element={<CompaniesPage />} />
          <Route path="/admin/memberships" element={<MembershipsPage />} />
          <Route path="/admin/overview" element={<OverviewPage />} />
          <Route path="/admin/users" element={<UsersPage />} />
          <Route path="/anomalies" element={<AnomaliesPage />} />
          <Route path="/cost-explorer" element={<CostExplorerPage />} />
          <Route path="/" element={<IndexPage />} />
          <Route path="/profile" element={<ProfilePage />} />
          <Route path="/reports" element={<ReportsPage />} />
          <Route path="/resources" element={<ResourcesPage />} />
          <Route path="/savings" element={<SavingsPage />} />
          <Route path="/settings" element={<SettingsPage />} />
          <Route path="/layout" element={<LayoutPage />} />
          <Route path="/admin/profile" element={<ProfilePage />} />
          </Route>
        </Routes>
      </BrowserRouter>
    </AuthProvider>
  );
}

export default App;
