// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import React from 'react';
import AdminShell from '../../layout/AdminShell';
import { useAdminMemberships } from '../../hooks/useAdminMemberships';

const MembershipsPage: React.FC = () => {
  const { membershipRows, createUserIds, setCreateUserIds, createCompanyId, setCreateCompanyId, createRole, setCreateRole, editRole, setEditRole, editUserName, editUserEmail, editCompanyName, filteredUserOptions, filteredCompanyOptions, openCreateModal, openEditModal, handleCreateSubmit, handleEditSubmit, toggleMembershipStatus, deleteMembership, membershipUserName, membershipStatusLabel, membershipToggleLabel, membershipRoleBadgeClass, membershipStatusBadgeClass } = useAdminMemberships();
  return (
    <AdminShell>
      <div className="container-fluid" style={{maxWidth: '1200px', padding: '32px 32px 80px'}}>
                  <div className="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4">
                      <div>
                          <h1 className="fw-bold text-body mb-1 h4">Memberships</h1><small className="text-muted">Link users to companies and manage access roles</small>
                      </div><button className="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#modalCreateMembership" data-cloudey="admin.memberships.open_create_btn" type="button" onClick={openCreateModal}><svg className="bi bi-link-45deg me-1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                              <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z"></path>
                              <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"></path>
                          </svg>Create Membership</button>
                  </div>
                  <div className="d-flex align-items-center flex-wrap gap-3 mb-4">
                      <div className="input-group" style={{maxWidth: '300px'}}><span className="text-muted bg-body-secondary input-group-text border-end-0"><svg className="bi bi-search" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '12px'}}>
                                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"></path>
                              </svg></span><input className="bg-body-secondary form-control border-start-0" type="text" placeholder="Search by users or companies..." style={{fontSize: '13px'}} /></div>
                      <ul className="nav nav-pills gap-1 mb-0" role="tablist">
                          <li className="nav-item"></li>
                          <li className="nav-item"></li>
                          <li className="nav-item"></li>
                          <li className="nav-item"></li>
                      </ul>
                  </div>
                  <div className="card border shadow-sm">
                      <div className="p-0 card-body">
                          <table className="table table-hover align-middle mb-0">
                              <thead>
                                  <tr>
                                      <th className="text-uppercase fw-semibold text-muted px-4" style={{fontSize: '10px', letterSpacing: '.5px', paddingBlock: '12px'}}>User</th>
                                      <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Email</th>
                                      <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Company</th>
                                      <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Role</th>
                                      <th className="text-uppercase fw-semibold text-muted" style={{fontSize: '10px', letterSpacing: '.5px'}}>Status</th>
                                      <th></th>
                                  </tr>
                              </thead>
                              <tbody>
        {membershipRows.map((membership) => (
          <tr key={`${membership.user_id}-${membership.company_id}`}>
                                      <td className="text-body px-4" style={{fontSize: '13px'}}>{membershipUserName(membership)}</td>
                                      <td className="text-muted" style={{fontSize: '12px'}}>{membership.user_email}</td>
                                      <td className="text-body" style={{fontSize: '13px'}}>{membership.company_name}</td>
                                      <td><span className={membershipRoleBadgeClass(membership.role)} style={{fontSize: '11px'}}>{membership.role}</span></td>
                                      <td><span className={membershipStatusBadgeClass(membership.active)} style={{fontSize: '11px'}}>{membershipStatusLabel(membership.active)}</span></td>
                                      <td className="pe-3">
                                          <div className="btn-group d-flex gap-1 btn-group" role="group"><button className="btn btn-outline-primary btn-sm" type="button" data-bs-target="#modalUpdateMembership" data-bs-toggle="modal" onClick={() => openEditModal(membership)}>Edit</button><button className="btn btn-outline-warning btn-sm py-1" type="button" onClick={() => void toggleMembershipStatus(membership)}>{membershipToggleLabel(membership)}</button><button className="btn btn-outline-danger btn-sm py-1" onClick={() => void deleteMembership(membership)}>Delete membership</button></div>
                                      </td>
                                  </tr>
        ))}
      </tbody>
                          </table>
                      </div>
                  </div>
                  <div className="modal fade" role="dialog" tabIndex={-1} id="modalCreateMembership">
                      <div className="modal-dialog modal-dialog-centered" role="document">
                          <div className="modal-content rounded-3">
                              <div className="modal-header border-bottom">
                                  <h6 className="modal-title fw-bold">Create Membership</h6><button className="btn-close" data-bs-dismiss="modal" type="button"></button>
                              </div>
                              <form data-cloudey="admin.memberships.create_form" onSubmit={handleCreateSubmit}>
                                  <div className="modal-body">
                                      <div className="alert alert-primary mb-4 py-2" role="alert" style={{fontSize: '12px'}}><span>A membership grants a user access to a company workspace. The user must already exist in the system.</span></div>
                                      <div className="mb-3"><label className="form-label fw-semibold" style={{fontSize: '13px'}}>User Email <span className="text-danger">*</span></label><select className="form-select form-select-sm form-select" data-cloudey="admin.memberships.create.user_id" multiple value={createUserIds} onChange={e => setCreateUserIds(Array.from(e.target.selectedOptions, (o) => o.value))}>{filteredUserOptions.map((u) => (<option key={u.user_id} value={u.user_id}>{u.email}</option>))}</select></div>
                                      <div className="mb-3"><label className="form-label fw-semibold" style={{fontSize: '13px'}}>Company <span className="text-danger">*</span></label><select className="form-select form-select-sm form-select" data-cloudey="admin.memberships.create.company_id" value={createCompanyId} onChange={e => setCreateCompanyId(e.target.value)}><option value="">Select company...</option>{filteredCompanyOptions.map((c) => (<option key={c.company_id} value={c.company_id}>{c.name}</option>))}</select></div>
                                      <div className="mb-3"><label className="form-label fw-semibold" style={{fontSize: '13px'}}>Role</label><select className="form-select form-select-sm form-select" data-cloudey="admin.memberships.create.role" value={createRole} onChange={e => setCreateRole(e.target.value)}>{['Owner', 'Admin', 'Member'].map((role) => (<option key={role} value={role}>{role}</option>))}</select></div>
                                  </div>
                                  <div className="modal-footer border-top"><button className="btn btn-primary btn-sm" type="submit"><svg className="bi bi-link-45deg me-1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                              <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z"></path>
                                              <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"></path>
                                          </svg>Create Membership</button><button className="btn btn-outline-secondary btn-sm" data-bs-dismiss="modal">Cancel</button></div>
                              </form>
                          </div>
                      </div>
                  </div>
                  <div className="modal fade" role="dialog" tabIndex={-1} id="modalUpdateMembership">
                      <div className="modal-dialog modal-dialog-centered" role="document">
                          <div className="modal-content rounded-3">
                              <div className="modal-header border-bottom">
                                  <h6 className="modal-title fw-bold">Update Membership</h6><button className="btn-close" data-bs-dismiss="modal" type="button"></button>
                              </div>
                              <form data-cloudey="admin.memberships.edit_form" onSubmit={handleEditSubmit}>
                                  <div className="modal-body">
                                      <div className="alert alert-primary mb-4 py-2" role="alert" style={{fontSize: '12px'}}><span>You can only modify the Role. To modify the User details you need to go to Users Section</span></div>
                                      <div className="mb-3"><label className="form-label fw-semibold" style={{fontSize: '13px'}}>User Name </label><label className="form-label border d-block form-control-sm" data-cloudey="admin.memberships.edit.user_name" data-cloudey-replace="admin.memberships.edit.user_name">{editUserName}</label></div>
                                      <div className="mb-3"><label className="form-label fw-semibold" style={{fontSize: '13px'}}>User Email </label><label className="form-label border d-block form-control-sm" data-cloudey="admin.memberships.edit.user_email" data-cloudey-replace="admin.memberships.edit.user_email">{editUserEmail}</label></div>
                                      <div className="mb-3"><label className="form-label fw-semibold" style={{fontSize: '13px'}}>Company </label><label className="form-label border d-block form-control-sm" data-cloudey="admin.memberships.edit.company_name" data-cloudey-replace="admin.memberships.edit.company_name">{editCompanyName}</label></div>
                                      <div className="mb-3"><label className="form-label fw-semibold" style={{fontSize: '13px'}}>Role</label><select className="form-select form-select-sm form-select" data-cloudey="admin.memberships.edit.role" value={editRole} onChange={e => setEditRole(e.target.value)} defaultValue="Member">
                                              <option value="Admin">Admin</option>
                                              <option value="Owner">Owner</option>
                                              <option value="Member">Member</option>
                                          </select></div>
                                  </div>
                                  <div className="modal-footer border-top"><button className="btn btn-primary btn-sm" type="submit"><svg className="bi bi-link-45deg me-1" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                              <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z"></path>
                                              <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"></path>
                                          </svg>Update Membership</button><button className="btn btn-outline-secondary btn-sm" data-bs-dismiss="modal">Cancel</button></div>
                              </form>
                          </div>
                      </div>
                  </div>
              </div>
    </AdminShell>
  );
};

export default MembershipsPage;
