// AUTO-GENERATED by bss_exporter/bss_to_react.py — do not edit.
// Wire UI in BSS (data-cloudey) + bss_exporter/templates/cloudey.config.json.
// Re-export from Bootstrap Studio to refresh this file.

import React from 'react';
import AdminShell from '../../layout/AdminShell';

const OverviewPage: React.FC = () => {
  return (
    <AdminShell>
      <div className="container-fluid" style={{maxWidth: '1200px', padding: '32px 32px 80px'}}>
                  <div className="mb-4">
                      <h1 className="fw-bold text-body mb-1 h4">Overview</h1><small className="text-muted">Platform health and revenue snapshot · May 2026</small>
                  </div>
                  <div className="row mb-4 g-3">
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body">
                                  <div className="d-flex align-items-center gap-2 mb-3">
                                      <div className="bg-success bg-opacity-10 rounded-2 d-flex justify-content-center align-items-center" style={{width: '32px', height: '32px'}}><svg className="bi bi-credit-card-fill text-success" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                              <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1H0zm0 3v5a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7zm3 2h1a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-1a1 1 0 0 1 1-1"></path>
                                          </svg></div><small className="fw-medium text-muted">Monthly Recurring Revenue</small>
                                  </div>
                                  <div className="text-success stat-value"><span>$1,576</span></div><small className="fw-semibold text-success"><svg className="bi bi-arrow-up-short" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                          <path fillRule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5"></path>
                                      </svg>+$299 this month</small>
                              </div>
                          </div>
                      </div>
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body">
                                  <div className="d-flex align-items-center gap-2 mb-3">
                                      <div className="bg-primary bg-opacity-10 rounded-2 d-flex justify-content-center align-items-center" style={{width: '32px', height: '32px'}}><svg className="bi bi-people-fill text-primary" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                              <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"></path>
                                          </svg></div><small className="fw-medium text-muted">Total Users</small>
                                  </div>
                                  <div className="text-primary stat-value"><span>10</span></div><small className="text-muted">8 active · 1 invited · 1 suspended</small>
                              </div>
                          </div>
                      </div>
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body">
                                  <div className="d-flex align-items-center gap-2 mb-3">
                                      <div className="rounded-2 d-flex justify-content-center align-items-center" style={{width: '32px', height: '32px', background: 'rgba(124,58,237,.1)'}}><svg className="bi bi-building" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px', color: '#7C3AED'}}>
                                              <path d="M4 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zM4 5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM7.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM4.5 8a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5z"></path>
                                              <path d="M2 1a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1zm11 0H3v14h3v-2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V15h3z"></path>
                                          </svg></div><small className="fw-medium text-muted">Companies</small>
                                  </div>
                                  <div className="stat-value" style={{color: '#7C3AED'}}><span>5</span></div><small className="text-muted">4 active · 1 trial</small>
                              </div>
                          </div>
                      </div>
                      <div className="col-md-6 col-xl-3">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body">
                                  <div className="d-flex align-items-center gap-2 mb-3">
                                      <div className="bg-warning bg-opacity-10 rounded-2 d-flex justify-content-center align-items-center" style={{width: '32px', height: '32px'}}><svg className="bi bi-cloud-fill text-warning" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                              <path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383"></path>
                                          </svg></div><small className="fw-medium text-muted">OCI Integrations</small>
                                  </div>
                                  <div className="text-warning stat-value"><span>4</span></div><small className="text-muted">Connected workspaces</small>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="row mb-4 g-4">
                      <div className="col-xl-7">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body p-4">
                                  <h6 className="fw-bold text-body mb-1">MRR Growth</h6><small className="text-muted d-block mb-4">Last 6 months</small>
                                  <div className="bg-body-secondary rounded-2 d-flex align-items-end gap-3 p-3" style={{height: '140px'}}>
                                      <div className="d-flex flex-column flex-grow-1 align-items-center gap-1">
                                          <div className="bg-primary bg-opacity-50 w-100 rounded-top" style={{height: '27%'}}></div><small className="text-muted" style={{fontSize: '10px'}}>Dec</small>
                                      </div>
                                      <div className="d-flex flex-column flex-grow-1 align-items-center gap-1">
                                          <div className="bg-primary bg-opacity-50 w-100 rounded-top" style={{height: '38%'}}></div><small className="text-muted" style={{fontSize: '10px'}}>Jan</small>
                                      </div>
                                      <div className="d-flex flex-column flex-grow-1 align-items-center gap-1">
                                          <div className="bg-primary bg-opacity-75 w-100 rounded-top" style={{height: '50%'}}></div><small className="text-muted" style={{fontSize: '10px'}}>Feb</small>
                                      </div>
                                      <div className="d-flex flex-column flex-grow-1 align-items-center gap-1">
                                          <div className="bg-primary bg-opacity-75 w-100 rounded-top" style={{height: '57%'}}></div><small className="text-muted" style={{fontSize: '10px'}}>Mar</small>
                                      </div>
                                      <div className="d-flex flex-column flex-grow-1 align-items-center gap-1">
                                          <div className="bg-primary w-100 rounded-top" style={{height: '76%'}}></div><small className="text-muted" style={{fontSize: '10px'}}>Apr</small>
                                      </div>
                                      <div className="d-flex flex-column flex-grow-1 align-items-center gap-1">
                                          <div className="bg-success w-100 rounded-top" style={{height: '100%'}}></div><small className="fw-bold text-success" style={{fontSize: '10px'}}>May</small>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="col-xl-5">
                          <div className="card border shadow-sm h-100">
                              <div className="card-body p-4">
                                  <h6 className="fw-bold text-body mb-1">Plan Distribution</h6><small className="text-muted d-block mb-4">Active subscriptions</small>
                                  <div className="mb-3">
                                      <div className="d-flex justify-content-between mb-1">
                                          <div className="d-flex align-items-center gap-2"><span className="rounded-circle" style={{width: '8px', height: '8px', display: 'inline-block', background: '#7C3AED'}}></span><small className="fw-medium text-body">Enterprise</small><small className="text-muted">1 co.</small></div><small className="fw-semibold text-body">$899/mo</small>
                                      </div>
                                      <div className="progress rounded-pill progress-xs">
                                          <div className="progress-bar" aria-valuenow={50} aria-valuemin={0} aria-valuemax={100} style={{width: '14%', background: '#7C3AED'}}><span className="visually-hidden">50%</span></div>
                                      </div>
                                  </div>
                                  <div className="mb-3">
                                      <div className="d-flex justify-content-between mb-1">
                                          <div className="d-flex align-items-center gap-2"><span className="rounded-circle" style={{width: '8px', height: '8px', display: 'inline-block', background: 'var(--bs-primary)'}}></span><small className="fw-medium text-body">Growth</small><small className="text-muted">3 co.</small></div><small className="fw-semibold text-body">$897/mo</small>
                                      </div>
                                      <div className="progress rounded-pill progress-xs">
                                          <div className="progress-bar bg-primary" aria-valuenow={50} aria-valuemin={0} aria-valuemax={100} style={{width: '43%'}}><span className="visually-hidden">50%</span></div>
                                      </div>
                                  </div>
                                  <div className="mb-3">
                                      <div className="d-flex justify-content-between mb-1">
                                          <div className="d-flex align-items-center gap-2"><span className="rounded-circle" style={{width: '8px', height: '8px', display: 'inline-block', background: '#3B82F6'}}></span><small className="fw-medium text-body">Starter</small><small className="text-muted">1 co.</small></div><small className="fw-semibold text-body">$79/mo</small>
                                      </div>
                                      <div className="progress rounded-pill progress-xs">
                                          <div className="progress-bar" aria-valuenow={50} aria-valuemin={0} aria-valuemax={100} style={{width: '14%', background: '#3B82F6'}}><span className="visually-hidden">50%</span></div>
                                      </div>
                                  </div>
                                  <div className="mb-3">
                                      <div className="d-flex justify-content-between mb-1">
                                          <div className="d-flex align-items-center gap-2"><span className="rounded-circle" style={{width: '8px', height: '8px', display: 'inline-block', background: 'var(--bs-secondary)'}}></span><small className="fw-medium text-body">Free Trial</small><small className="text-muted">2 co.</small></div><small className="fw-semibold text-body">—</small>
                                      </div>
                                      <div className="progress rounded-pill progress-xs">
                                          <div className="progress-bar bg-secondary" aria-valuenow={50} aria-valuemin={0} aria-valuemax={100} style={{width: '29%'}}><span className="visually-hidden">50%</span></div>
                                      </div>
                                  </div>
                                  <div className="d-flex justify-content-between mt-2 pt-3 border-top"><small className="text-muted">Total MRR</small><span className="fw-bold text-success" style={{fontSize: '16px'}}>$1,576/mo</span></div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="card border shadow-sm">
                      <div className="card-body p-4">
                          <h6 className="fw-bold text-body mb-1">Recent Activity</h6><small className="text-muted d-block mb-4">Latest admin and system actions</small>
                          <div className="d-flex flex-column">
                              <div className="d-flex align-items-start gap-3 py-3 border-bottom">
                                  <div className="rounded-2 d-flex flex-shrink-0 justify-content-center align-items-center" style={{width: '32px', height: '32px', background: 'rgba(16,185,129,.1)', color: '#10B981'}}><svg className="bi bi-credit-card" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                          <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v1h14V4a1 1 0 0 0-1-1zm13 4H1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1z"></path>
                                          <path d="M2 10a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"></path>
                                      </svg></div>
                                  <div className="flex-grow-1">
                                      <div className="fw-medium text-body" style={{fontSize: '13px'}}><span>Subscription renewed: CloudPrime Enterprise</span></div><small className="text-muted">System · May 1 2026, 00:00</small>
                                  </div><span className="badge fw-semibold rounded-pill" style={{fontSize: '10px', background: 'rgba(16,185,129,.1)', color: '#10B981'}}>billing</span>
                              </div>
                              <div className="d-flex align-items-start gap-3 py-3 border-bottom">
                                  <div className="rounded-2 d-flex flex-shrink-0 justify-content-center align-items-center" style={{width: '32px', height: '32px', background: 'rgba(6,182,212,.1)', color: 'var(--bs-primary)'}}><svg className="bi bi-person-plus" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                          <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"></path>
                                          <path fillRule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"></path>
                                      </svg></div>
                                  <div className="flex-grow-1">
                                      <div className="fw-medium text-body" style={{fontSize: '13px'}}><span>Created user quinn@devly.com</span></div><small className="text-muted">Alex Morgan · Apr 21 2026, 14:32</small>
                                  </div><span className="badge fw-semibold rounded-pill" style={{fontSize: '10px', background: 'rgba(6,182,212,.1)', color: 'var(--bs-primary)'}}>create</span>
                              </div>
                              <div className="d-flex align-items-start gap-3 py-3 border-bottom">
                                  <div className="rounded-2 d-flex flex-shrink-0 justify-content-center align-items-center" style={{width: '32px', height: '32px', background: 'rgba(239,68,68,.1)', color: '#EF4444'}}><svg className="bi bi-shield-exclamation" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                          <path d="M5.338 1.59a61 61 0 0 0-2.837.856.48.48 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.7 10.7 0 0 0 2.287 2.233c.346.244.652.42.893.533q.18.085.293.118a1 1 0 0 0 .101.025 1 1 0 0 0 .1-.025q.114-.034.294-.118c.24-.113.547-.29.893-.533a10.7 10.7 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.8 11.8 0 0 1-2.517 2.453 7 7 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7 7 0 0 1-1.048-.625 11.8 11.8 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 63 63 0 0 1 5.072.56"></path>
                                          <path d="M7.001 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.553.553 0 0 1-1.1 0z"></path>
                                      </svg></div>
                                  <div className="flex-grow-1">
                                      <div className="fw-medium text-body" style={{fontSize: '13px'}}><span>Failed login attempt: unknown@hax.io</span></div><small className="text-muted">System · Apr 29 2026, 03:11</small>
                                  </div><span className="badge fw-semibold rounded-pill" style={{fontSize: '10px', background: 'rgba(239,68,68,.1)', color: '#EF4444'}}>security</span>
                              </div>
                              <div className="d-flex align-items-start gap-3 py-3">
                                  <div className="rounded-2 d-flex flex-shrink-0 justify-content-center align-items-center" style={{width: '32px', height: '32px', background: 'rgba(124,58,237,.1)', color: '#7C3AED'}}><svg className="bi bi-toggles" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" style={{fontSize: '13px'}}>
                                          <path d="M4.5 9a3.5 3.5 0 1 0 0 7h7a3.5 3.5 0 1 0 0-7zm7 6a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5m-7-14a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5m2.45 0A3.5 3.5 0 0 1 8 3.5 3.5 3.5 0 0 1 6.95 6h4.55a2.5 2.5 0 0 0 0-5zM4.5 0h7a3.5 3.5 0 1 1 0 7h-7a3.5 3.5 0 1 1 0-7"></path>
                                      </svg></div>
                                  <div className="flex-grow-1">
                                      <div className="fw-medium text-body" style={{fontSize: '13px'}}><span>Feature flag enabled: AI Chat Widget</span></div><small className="text-muted">Alex Morgan · Mar 5 2026, 15:22</small>
                                  </div><span className="badge fw-semibold rounded-pill" style={{fontSize: '10px', background: 'rgba(124,58,237,.1)', color: '#7C3AED'}}>system</span>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
    </AdminShell>
  );
};

export default OverviewPage;
