import React from 'react';
import { Outlet } from 'react-router-dom';
import { useCloudey } from '../hooks/useCloudey';

/**
 * AppLayout
 * Wraps all authenticated pages. Provides sidebar/topbar shell
 * and wires up Cloudey UI interactions via useCloudey().
 * Auto-generated by bss_to_react.py — do not edit manually.
 */
const AppLayout: React.FC = () => {
  useCloudey();
  return <Outlet />;
};

export default AppLayout;
